### ISSUE TITLE
Game "moves" after one level

### ISSUE THREAD

**Issue by rspencer01** [jacquesh/LostLuggage#2]
When a new level is loaded, the game "shifts" to the bottom right a little.

**Comment by jacquesh** [comment]
Didn't realise at the time, but as with #1, this is fixed by 01d662a.
What was happening is that it would set the camera position, then load a level which first re-does that camera positioning, and then shrinks grid_size as necessary to fit the level.

I'm not really a fan of shrinking grid_size like that but I understand why we need it and it doesn't really matter at the moment so a nicer solution can be done later if necessary.
